#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xff90;
constexpr uint24_t FX_DATA_BYTES = 28456;

constexpr uint24_t aboy = 0x000000;
constexpr uint24_t box = 0x000422;
constexpr uint24_t dcube = 0x0005D4;
constexpr uint24_t dshaddowb = 0x000786;
constexpr uint24_t dshaddowc = 0x0007D0;
constexpr uint24_t dshaddowd = 0x00081A;
constexpr uint24_t dshaddow = 0x000864;
constexpr uint24_t explodea = 0x0008AE;
constexpr uint24_t explodeb = 0x000A60;
constexpr uint24_t explodec = 0x000C12;
constexpr uint24_t exploded = 0x000DC4;
constexpr uint24_t explodee = 0x000F76;
constexpr uint24_t explodef = 0x001128;
constexpr uint24_t gameover = 0x0012DA;
constexpr uint24_t grid = 0x001EAC;
constexpr uint24_t hglitch = 0x0034CE;
constexpr uint24_t lifei = 0x0039B0;
constexpr uint24_t lshaddowb = 0x0039C4;
constexpr uint24_t lshaddowc = 0x003A0E;
constexpr uint24_t lshaddowd = 0x003A58;
constexpr uint24_t lshaddow = 0x003AA2;
constexpr uint24_t newaboy = 0x003AEC;
constexpr uint24_t onebit = 0x003F0E;
constexpr uint24_t playerb = 0x004228;
constexpr uint24_t playerc = 0x0042EA;
constexpr uint24_t playerd = 0x0043AC;
constexpr uint24_t player = 0x00446E;
constexpr uint24_t productions = 0x004530;
constexpr uint24_t scube = 0x004ADE;
constexpr uint24_t shaddowb = 0x004C90;
constexpr uint24_t shaddowc = 0x004CDA;
constexpr uint24_t shaddowd = 0x004D24;
constexpr uint24_t shaddow = 0x004D6E;
constexpr uint24_t speaker = 0x004DB8;
constexpr uint24_t ssound = 0x004F52;
constexpr uint24_t tes = 0x004FA8;
constexpr uint24_t title = 0x0050CA;
constexpr uint24_t vcube = 0x005C6C;
constexpr uint24_t vglitch = 0x005E1E;
constexpr uint24_t wonebit = 0x006660;
constexpr uint24_t wproductions = 0x00697A;
